spring.application.name=AeroCartSpringEcom

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AeroCartEcom
spring.datasource.username=postgres
spring.datasource.password=123123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# Optional: This shows the SQL Spring is running in your console
spring.jpa.show-sql=true

# Connection Pool Settings (Optional but Recommended)
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# SQL Logging (Helpful for debugging)
logging.level.org.springframework.jdbc.core=DEBUG
